services:
  - type: web
    name: match-commissioner
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MONGO_URI
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_API_KEY
        sync: false
      - key: KAFKA_API_SECRET
        sync: false
      - key: KAFKA_MECHANISM
        value: SCRAM-SHA-256
      - key: JWT_SECRET
        sync: false
      - key: SERVER_CONTEXT_PATH
        value: /api/v1

# 